spring:
  thymeleaf:
    mode: HTML
    #prefix: file:<path of the templates>
    prefix: classpath:/templates/pages/
    cache: false
    content-type: text/html
    encoding: UTF-8
    suffix: .html
    check-template-location: true
  application:
    name: bazel-springboot
  main:
    banner-mode: "off"

app:
  jdbcUrl: "jdbc:sqlite:/tmp/test-domain.db"
