spring:
  thymeleaf:
    mode: HTML
    #prefix: file:<path of the templates>
    prefix: classpath:/templates/pages/
    cache: false
    content-type: text/html
    encoding: UTF-8
    suffix: .html
    check-template-location: true
  web:
    resources:
      static-locations: classpath:/assets/
  application:
    name: bazel-springboot
  main:
    banner-mode: "off"